use super::*;
use serde::Serialize;

fn assert_round_trip<T>(value: &T)
where
    T: Serialize + for<'de> Deserialize<'de>,
{
    let json = serde_json::to_value(value).expect("value should serialize");
    let decoded = serde_json::from_value::<T>(json).expect("value should deserialize");
    let decoded_json = serde_json::to_value(decoded).expect("decoded value should serialize");
    let original_json = serde_json::to_value(value).expect("original value should serialize");
    assert_eq!(decoded_json, original_json);
}

#[test]
fn runtime_result_types_round_trip_through_serde_json() {
    let tick = GoalTickResult {
        schema_version: "goal_tick_result.v1".to_string(),
        status: "advanced".to_string(),
        project_id: "project_fixture".to_string(),
        routine_run_due: crate::routines::RoutineRunDueResult {
            status: "ok".to_string(),
            selected_count: 1,
            triggered_count: 1,
            failed_count: 0,
            outcomes: vec![crate::routines::RoutineRunDueOutcome {
                status: "triggered".to_string(),
                ingress: crate::routines::RoutineIngressRecord {
                    schema_version: "routine_ingress.v1".to_string(),
                    ingress_id: "ingress_1".to_string(),
                    routine_id: "routine_1".to_string(),
                    trigger_kind: "manual".to_string(),
                    source: "operator".to_string(),
                    dedupe_key: String::new(),
                    status: "ready".to_string(),
                    decision: "accept".to_string(),
                    received_at: "1".to_string(),
                    ready_at: "1".to_string(),
                    duplicate_of_ingress_id: String::new(),
                    triggered_at: String::new(),
                    trigger_id: String::new(),
                    run_id: String::new(),
                    agent_id: String::new(),
                    lease_id: String::new(),
                    trigger_record_path: String::new(),
                },
                trigger_result: None,
                error: None,
            }],
            recovery_governance: crate::routines::RoutineRecoveryGovernanceSummary {
                schema_version: "routine.recovery_governance_summary.v1".to_string(),
                status: "ok".to_string(),
                failed_trigger_count: 0,
                retryable_trigger_count: 0,
                budget_exhausted_count: 0,
                backoff_active_count: 0,
                pending_ingress_failure_count: 0,
                next_recommended_action: "continue".to_string(),
                entries: Vec::new(),
            },
        },
        goal_advance: crate::goals::GoalAdvanceResult {
            schema_version: "goal_advance_result.v1".to_string(),
            status: "advanced".to_string(),
            action: "advance".to_string(),
            project_id: "project_fixture".to_string(),
            mission_frame_ref: "mission_frame_ref".to_string(),
            run: crate::orchestration::OrchestrationRun::new("run_1", "objective", "start"),
            dispatches: Vec::new(),
            dispatch: None,
            acceptance: None,
            stage_decision: None,
            task_pool: crate::goals::GoalTaskPoolSnapshot {
                schema_version: "goal_task_pool_snapshot.v1".to_string(),
                authority_model: "main_agent".to_string(),
                source: "fixture".to_string(),
                project_id: "project_fixture".to_string(),
                automation_mode: crate::goals::GoalAutomationMode::HighAutonomy,
                target_run: None,
                summary: crate::goals::GoalTaskPoolSummary::default(),
                entries: Vec::new(),
                next_recommended_action: "continue".to_string(),
            },
            next_recommended_action: "continue".to_string(),
            warnings: Vec::new(),
        },
        triggered_count: 1,
        dispatch_count: 1,
        accepted: true,
        next_recommended_action: "continue".to_string(),
        recovery_governance: crate::routines::RoutineRecoveryGovernanceSummary {
            schema_version: "routine.recovery_governance_summary.v1".to_string(),
            status: "ok".to_string(),
            failed_trigger_count: 0,
            retryable_trigger_count: 0,
            budget_exhausted_count: 0,
            backoff_active_count: 0,
            pending_ingress_failure_count: 0,
            next_recommended_action: "continue".to_string(),
            entries: Vec::new(),
        },
        loop_closure: crate::goals::GoalLoopClosureProjection {
            schema_version: "goal_loop_closure.v1".to_string(),
            status: "running".to_string(),
            automation_mode: crate::goals::GoalAutomationMode::HighAutonomy,
            should_continue: true,
            next_recommended_action: "continue".to_string(),
            main_agent_instruction: "continue".to_string(),
            pause_reason: None,
            target_run_status: None,
            target_run_progress_percent: None,
            task_pool_summary: crate::goals::GoalTaskPoolSummary::default(),
            recovery_governance_status: None,
            recovery_governance_action: None,
            open_recovery_wake_count: 0,
            dispatch_count: 1,
            accepted: true,
        },
    };

    let watch = GoalWatchResult {
        schema_version: "goal_watch_result.v1".to_string(),
        status: "ok".to_string(),
        project_id: "project_fixture".to_string(),
        interval_ms: 2500,
        ticks_completed: 1,
        stop_reason: "loop_completed".to_string(),
        watch_lock_path: ".pmcli/goals/goals_watch.lock".to_string(),
        watch_state_path: ".pmcli/goals/goals_watch.json".to_string(),
        last_tick: Some(tick.clone()),
    };

    let job_state = AutonomousResearchJobState {
        schema_version: "autonomous_research_job.v1".to_string(),
        job_id: "arj_fixture".to_string(),
        project_id: "project_fixture".to_string(),
        prompt: "fixture prompt".to_string(),
        workflow_profile: default_autonomous_workflow_profile(),
        status: "running".to_string(),
        phase: "stage_review".to_string(),
        automation_mode: crate::goals::GoalAutomationMode::FullAuto,
        permission_mode: "workspace-write".to_string(),
        review_model: Some("gpt-fixture".to_string()),
        stage_task_semantic_review_mode: default_stage_task_semantic_review_mode(),
        created_at: "1".to_string(),
        updated_at: "1".to_string(),
        max_ticks: 10,
        ticks_completed: 1,
        interval_ms: 1000,
        max_runtime_ms: 10000,
        max_review_rounds: 3,
        review_rounds_completed: 1,
        report_path: "report.md".to_string(),
        job_state_path: "job.json".to_string(),
        job_events_path: "events.jsonl".to_string(),
        runner_log_path: "runner.log".to_string(),
        thread_id: Some("thread_fixture".to_string()),
        stage_execution_id: Some("stage_fixture".to_string()),
        session_id: Some("sess_fixture".to_string()),
        background_pid: Some(42),
        stop_reason: None,
        last_error: None,
        last_review: Some(AutonomousResearchReviewState {
            review_id: "review_fixture".to_string(),
            verdict: "pass".to_string(),
            score: Some(91),
            response_text: "pass".to_string(),
            target_path: "target.md".to_string(),
            rubric_path: None,
            review_summary_path: None,
            created_at: "1".to_string(),
        }),
        last_loop_closure: Some(crate::goals::GoalLoopClosureProjection {
            schema_version: "goal_loop_closure.v1".to_string(),
            status: "running".to_string(),
            automation_mode: crate::goals::GoalAutomationMode::FullAuto,
            should_continue: true,
            next_recommended_action: "continue".to_string(),
            main_agent_instruction: "continue".to_string(),
            pause_reason: None,
            target_run_status: None,
            target_run_progress_percent: None,
            task_pool_summary: crate::goals::GoalTaskPoolSummary::default(),
            recovery_governance_status: None,
            recovery_governance_action: None,
            open_recovery_wake_count: 0,
            dispatch_count: 0,
            accepted: false,
        }),
        tick_summaries: vec![AutonomousResearchTickSummary {
            tick_index: 1,
            status: "advanced".to_string(),
            dispatch_count: 0,
            accepted: true,
            loop_status: "running".to_string(),
            next_recommended_action: "continue".to_string(),
        }],
        artifact_refs: vec!["artifact_ref".to_string()],
        warnings: vec!["warn".to_string()],
        cleanup_plan_ids: vec!["cleanup_1".to_string()],
        failure_patterns: Vec::new(),
        obligations: Vec::new(),
        continuity_packets: Vec::new(),
        provider_faults: Vec::new(),
        active_provider_fault: None,
        provider_rounds: vec![AutonomousResearchAgentRoundSummary {
            round_index: 1,
            artifact_path: "round.md".to_string(),
            runtime_identity_ref: Some("runtime_identity_ref".to_string()),
            provider_id: "provider".to_string(),
            model: "model".to_string(),
            provider_route_source: Some("fixture".to_string()),
            execution_mode: "test".to_string(),
            iterations: 1,
            tool_calls_made: 0,
            finish_reason: "completed".to_string(),
            content_sha256: "sha256-fixture".to_string(),
        }],
    };

    assert_round_trip(&tick);
    assert_round_trip(&watch);
    assert_round_trip(&AutonomousResearchJobRunResult {
        schema_version: "autonomous_research_job_run_result.v1".to_string(),
        status: "started".to_string(),
        project_id: "project_fixture".to_string(),
        job_id: "arj_fixture".to_string(),
        background: true,
        pid: Some(1234),
        job_state_path: "job.json".to_string(),
        job_events_path: "events.jsonl".to_string(),
        runner_log_path: "runner.log".to_string(),
        status_command: vec![
            "research".to_string(),
            "jobs".to_string(),
            "status".to_string(),
        ],
        tail_command: vec![
            "research".to_string(),
            "jobs".to_string(),
            "tail".to_string(),
        ],
        resume_command: vec![
            "research".to_string(),
            "jobs".to_string(),
            "resume".to_string(),
        ],
        tick_command: vec![
            "research".to_string(),
            "jobs".to_string(),
            "tick".to_string(),
        ],
        job: job_state.clone(),
    });
    assert_round_trip(&AutonomousResearchJobTickResult {
        schema_version: "autonomous_research_job_tick_result.v1".to_string(),
        status: "ticked".to_string(),
        project_id: "project_fixture".to_string(),
        job_id: "arj_fixture".to_string(),
        tick_index: 1,
        job_status: "running".to_string(),
        phase: "stage_review".to_string(),
        should_continue: true,
        review_passed: true,
        tick_summary: Some(AutonomousResearchTickSummary {
            tick_index: 1,
            status: "advanced".to_string(),
            dispatch_count: 0,
            accepted: true,
            loop_status: "running".to_string(),
            next_recommended_action: "continue".to_string(),
        }),
        review: job_state.last_review.clone(),
        job: job_state.clone(),
    });
    assert_round_trip(&AutonomousResearchJobListResult {
        schema_version: "autonomous_research_job_list_result.v1".to_string(),
        project_id: "project_fixture".to_string(),
        jobs: vec![job_state.clone()],
        total_count: 1,
    });
    assert_round_trip(&AutonomousResearchJobTailResult {
        schema_version: "autonomous_research_job_tail_result.v1".to_string(),
        project_id: "project_fixture".to_string(),
        job_id: "arj_fixture".to_string(),
        events_path: "events.jsonl".to_string(),
        events: vec![serde_json::json!({"event": "created"})],
    });
}
